DROP TYPE IF EXISTS "AuthProvider" CASCADE;
DROP TYPE IF EXISTS "Gender" CASCADE;
DROP TYPE IF EXISTS "RoomPriority" CASCADE;
DROP TYPE IF EXISTS "RoomStatus" CASCADE;
DROP TYPE IF EXISTS "SettlementStatus" CASCADE;
DROP TYPE IF EXISTS "SettlementRole" CASCADE;
DROP TYPE IF EXISTS "WalletTxKind" CASCADE;
DROP TYPE IF EXISTS "WalletTxStatus" CASCADE;
DROP TYPE IF EXISTS "NoticeType" CASCADE;
DROP TYPE IF EXISTS "RoomParticipantStatus" CASCADE; -- 있다면
DROP TYPE IF EXISTS "RideHistoryStatus" CASCADE;      -- 등등
